import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    description: "El iPhone más avanzado con chip A17 Pro, cámara de 48MP y pantalla Super Retina XDR.",
    price: 1299.99,
    image: "/15.jpg?height=400&width=400",
    category: "iphones",
    stock: 10,
    discount: 0,
    featured: true,
  },
  {
    id: "2",
    name: "iPhone 15",
    description: "Potencia y rendimiento con el nuevo chip A16 Bionic y cámara mejorada.",
    price: 899.99,
    image: "/155.jpg?height=400&width=400",
    category: "iphones",
    stock: 15,
    discount: 5,
    featured: false,
  },
  {
    id: "3",
    name: "Funda de silicona MagSafe para iPhone 15 Pro",
    description: "Protección elegante con imanes integrados para una conexión perfecta.",
    price: 49.99,
    image: "/ff.jpg?height=400&width=400",
    category: "fundas",
    stock: 25,
    discount: 0,
    featured: true,
  },
  {
    id: "4",
    name: "Cargador rápido USB-C de 30W",
    description: "Carga tu iPhone hasta un 50% en solo 30 minutos.",
    price: 39.99,
    image: "/c.jpg?height=400&width=400",
    category: "cargadores",
    stock: 30,
    discount: 10,
    featured: true,
  },
  {
    id: "5",
    name: "AirPods Pro 2",
    description: "Cancelación de ruido activa, audio espacial y resistencia al agua y sudor.",
    price: 249.99,
    image: "/air.jpg?height=400&width=400",
    category: "accesorios",
    stock: 8,
    discount: 0,
    featured: true,
  },
  {
    id: "6",
    name: "iPhone 14 Pro",
    description: "Pantalla siempre activa, Dynamic Island y cámara de 48MP.",
    price: 999.99,
    image: "/14.jpg?height=400&width=400",
    category: "iphones",
    stock: 5,
    discount: 15,
    featured: false,
  },
  {
    id: "7",
    name: "Funda de cuero para iPhone 15",
    description: "Elegante funda de cuero genuino con acabado premium.",
    price: 59.99,
    image: "/fundaC.jpg?height=400&width=400",
    category: "fundas",
    stock: 12,
    discount: 0,
    featured: false,
  },
  {
    id: "8",
    name: "Cargador inalámbrico MagSafe",
    description: "Carga inalámbrica rápida con alineación magnética perfecta.",
    price: 39.99,
    image: "/c.jpg?height=400&width=400",
    category: "cargadores",
    stock: 20,
    discount: 0,
    featured: false,
  },
  {
    id: "9",
    name: "Apple Watch Series 9",
    description: "El Apple Watch más potente con nuevas funciones de salud y fitness.",
    price: 399.99,
    image: "/r.jpg?height=400&width=400",
    category: "accesorios",
    stock: 7,
    discount: 0,
    featured: false,
  },
  {
    id: "10",
    name: "iPhone 13",
    description: "Pantalla Super Retina XDR, chip A15 Bionic y sistema de cámara dual avanzado.",
    price: 699.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "iphones",
    stock: 0,
    discount: 20,
    featured: false,
  },
  {
    id: "11",
    name: "Protector de pantalla de vidrio templado",
    description: "Protección resistente a rayones con instalación fácil sin burbujas.",
    price: 19.99,
    image: "/t.jpg?height=400&width=400",
    category: "accesorios",
    stock: 50,
    discount: 25,
    featured: false,
  },
  {
    id: "12",
    name: "Cable USB-C a Lightning de 2m",
    description: "Cable de carga rápida y transferencia de datos de alta velocidad.",
    price: 29.99,
    image: "/l.jpg?height=400&width=400",
    category: "cargadores",
    stock: 35,
    discount: 0,
    featured: false,
  },
]
